apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: traffic-service-scaler
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traffic-service
  targetCPUUtilizationPercentage: 50