apiVersion: apps/v1 
kind: Deployment
metadata:
  name: weather-service
spec:
  selector:
    matchLabels:
      app: weather-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: weather-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer