#
# Build stage
#
FROM maven:3.6-adoptopenjdk-14 AS build

COPY ./src/ /home/traffic-service/src
COPY ./pom.xml /home/traffic-service/pom.xml

RUN ls -a /home/traffic-service
RUN mvn -f /home/traffic-service/pom.xml clean package

#
# Package stage
#
FROM adoptopenjdk:14-jdk-hotspot
COPY --from=build /home/traffic-service/target/*.jar /usr/local/lib/traffic-service.jar
EXPOSE 8080
# Run with "--enable-preview" because the application uses preview features.
ENTRYPOINT ["java", "--enable-preview","-jar","/usr/local/lib/traffic-service.jar"]